services:
  mongo:
    image: mongo:5.0.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - '${MONGO_PORT}:27017'
    networks:
      - backend
  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASS}
    environment:
      - REDIS_REPLICATION_NODE=master
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - backend
  auth:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.auth
    environment:
      - REDIS_URL=redis:${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - MONGO_URL=mongo:${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - SALT=${SALT}
      - JWT_LIFETIME_DAYS=${JWT_LIFETIME_DAYS}
    ports:
      - '${AUTH_PORT}:4000'
    depends_on:
      - mongo
      - redis
    networks:
      - backend
  dashboard:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dashboard
    environment:
      - REDIS_URL=redis:${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - MONGO_URL=mongo:${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - SALT=${SALT}
      - JWT_LIFETIME_DAYS=${JWT_LIFETIME_DAYS}
    ports:
      - '${DASHBOARD_PORT}:4001'
    depends_on:
      - mongo
      - redis
    networks:
      - backend
  exercise:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.exercise
    environment:
      - REDIS_URL=redis:${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - MONGO_URL=mongo:${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - SALT=${SALT}
      - JWT_LIFETIME_DAYS=${JWT_LIFETIME_DAYS}
    ports:
      - '${EXCERCISE_PORT}:4002'
    depends_on:
      - mongo
      - redis
    networks:
      - backend
  group:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.group
    environment:
      - REDIS_URL=redis:${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - MONGO_URL=mongo:${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - SALT=${SALT}
      - JWT_LIFETIME_DAYS=${JWT_LIFETIME_DAYS}
    ports:
      - '${GROUP_PORT}:4004'
    depends_on:
      - mongo
      - redis
    networks:
      - backend
  collection:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.collection
    environment:
      - REDIS_URL=redis:${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - MONGO_URL=mongo:${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - SALT=${SALT}
      - JWT_LIFETIME_DAYS=${JWT_LIFETIME_DAYS}
    ports:
      - '${COLLECTION_PORT}:4003'
    depends_on:
      - mongo
      - redis
    networks:
      - backend
networks:
  backend:
