// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/conabit/englearn/exercise/word_service.proto

package exercise

import (
	context "context"
	common "github.com/Conabit-Corp/EngLearn/proto/conabit/englearn/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Word_1Value string `protobuf:"bytes,2,opt,name=word_1_value,json=word1Value,proto3" json:"word_1_value,omitempty"`
	Word_1Code  string `protobuf:"bytes,3,opt,name=word_1_code,json=word1Code,proto3" json:"word_1_code,omitempty"`
	Word_2Value string `protobuf:"bytes,4,opt,name=word_2_value,json=word2Value,proto3" json:"word_2_value,omitempty"`
	Word_2Code  string `protobuf:"bytes,5,opt,name=word_2_code,json=word2Code,proto3" json:"word_2_code,omitempty"`
}

func (x *WordPair) Reset() {
	*x = WordPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordPair) ProtoMessage() {}

func (x *WordPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordPair.ProtoReflect.Descriptor instead.
func (*WordPair) Descriptor() ([]byte, []int) {
	return file_proto_conabit_englearn_exercise_word_service_proto_rawDescGZIP(), []int{0}
}

func (x *WordPair) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WordPair) GetWord_1Value() string {
	if x != nil {
		return x.Word_1Value
	}
	return ""
}

func (x *WordPair) GetWord_1Code() string {
	if x != nil {
		return x.Word_1Code
	}
	return ""
}

func (x *WordPair) GetWord_2Value() string {
	if x != nil {
		return x.Word_2Value
	}
	return ""
}

func (x *WordPair) GetWord_2Code() string {
	if x != nil {
		return x.Word_2Code
	}
	return ""
}

type RegisterWordPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session  *common.Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	WordPair *WordPair       `protobuf:"bytes,2,opt,name=word_pair,json=wordPair,proto3" json:"word_pair,omitempty"`
}

func (x *RegisterWordPairRequest) Reset() {
	*x = RegisterWordPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWordPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWordPairRequest) ProtoMessage() {}

func (x *RegisterWordPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWordPairRequest.ProtoReflect.Descriptor instead.
func (*RegisterWordPairRequest) Descriptor() ([]byte, []int) {
	return file_proto_conabit_englearn_exercise_word_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWordPairRequest) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RegisterWordPairRequest) GetWordPair() *WordPair {
	if x != nil {
		return x.WordPair
	}
	return nil
}

type CloneWordPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sesion   *common.Session `protobuf:"bytes,1,opt,name=sesion,proto3" json:"sesion,omitempty"`
	WordPair *WordPair       `protobuf:"bytes,2,opt,name=word_pair,json=wordPair,proto3" json:"word_pair,omitempty"`
}

func (x *CloneWordPairRequest) Reset() {
	*x = CloneWordPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneWordPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneWordPairRequest) ProtoMessage() {}

func (x *CloneWordPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneWordPairRequest.ProtoReflect.Descriptor instead.
func (*CloneWordPairRequest) Descriptor() ([]byte, []int) {
	return file_proto_conabit_englearn_exercise_word_service_proto_rawDescGZIP(), []int{2}
}

func (x *CloneWordPairRequest) GetSesion() *common.Session {
	if x != nil {
		return x.Sesion
	}
	return nil
}

func (x *CloneWordPairRequest) GetWordPair() *WordPair {
	if x != nil {
		return x.WordPair
	}
	return nil
}

var File_proto_conabit_englearn_exercise_word_service_proto protoreflect.FileDescriptor

var file_proto_conabit_englearn_exercise_word_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2f,
	0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73,
	0x65, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e,
	0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x1a,
	0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2f, 0x65,
	0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a,
	0x08, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x77, 0x6f, 0x72,
	0x64, 0x5f, 0x31, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x77, 0x6f, 0x72, 0x64, 0x31, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x77,
	0x6f, 0x72, 0x64, 0x5f, 0x31, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x31, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x77,
	0x6f, 0x72, 0x64, 0x5f, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a,
	0x0b, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x32, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x97, 0x01,
	0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6e,
	0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x70, 0x61,
	0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x61, 0x62,
	0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e, 0x65, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x43, 0x6c, 0x6f, 0x6e,
	0x65, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x38, 0x0a, 0x06, 0x73, 0x65, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x73, 0x65, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x09, 0x77, 0x6f,
	0x72, 0x64, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x2e, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x32, 0xc1, 0x02, 0x0a,
	0x0b, 0x57, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x10,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72,
	0x12, 0x32, 0x2e, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x2e, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65,
	0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x2e, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x0d, 0x43,
	0x6c, 0x6f, 0x6e, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x12, 0x2f, 0x2e, 0x63,
	0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e,
	0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x2e, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61,
	0x69, 0x72, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2e,
	0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x61, 0x62, 0x69,
	0x74, 0x2e, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2e, 0x65, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x69, 0x72, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43,
	0x6f, 0x6e, 0x61, 0x62, 0x69, 0x74, 0x2d, 0x43, 0x6f, 0x72, 0x70, 0x2f, 0x45, 0x6e, 0x67, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x61, 0x62,
	0x69, 0x74, 0x2f, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2f, 0x65, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_conabit_englearn_exercise_word_service_proto_rawDescOnce sync.Once
	file_proto_conabit_englearn_exercise_word_service_proto_rawDescData = file_proto_conabit_englearn_exercise_word_service_proto_rawDesc
)

func file_proto_conabit_englearn_exercise_word_service_proto_rawDescGZIP() []byte {
	file_proto_conabit_englearn_exercise_word_service_proto_rawDescOnce.Do(func() {
		file_proto_conabit_englearn_exercise_word_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_conabit_englearn_exercise_word_service_proto_rawDescData)
	})
	return file_proto_conabit_englearn_exercise_word_service_proto_rawDescData
}

var file_proto_conabit_englearn_exercise_word_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_conabit_englearn_exercise_word_service_proto_goTypes = []interface{}{
	(*WordPair)(nil),                // 0: conabit.englearn.exercise.WordPair
	(*RegisterWordPairRequest)(nil), // 1: conabit.englearn.exercise.RegisterWordPairRequest
	(*CloneWordPairRequest)(nil),    // 2: conabit.englearn.exercise.CloneWordPairRequest
	(*common.Session)(nil),          // 3: conabit.englearn.common.Session
}
var file_proto_conabit_englearn_exercise_word_service_proto_depIdxs = []int32{
	3, // 0: conabit.englearn.exercise.RegisterWordPairRequest.session:type_name -> conabit.englearn.common.Session
	0, // 1: conabit.englearn.exercise.RegisterWordPairRequest.word_pair:type_name -> conabit.englearn.exercise.WordPair
	3, // 2: conabit.englearn.exercise.CloneWordPairRequest.sesion:type_name -> conabit.englearn.common.Session
	0, // 3: conabit.englearn.exercise.CloneWordPairRequest.word_pair:type_name -> conabit.englearn.exercise.WordPair
	1, // 4: conabit.englearn.exercise.WordService.RegisterWordPair:input_type -> conabit.englearn.exercise.RegisterWordPairRequest
	2, // 5: conabit.englearn.exercise.WordService.CloneWordPair:input_type -> conabit.englearn.exercise.CloneWordPairRequest
	3, // 6: conabit.englearn.exercise.WordService.FindUserWords:input_type -> conabit.englearn.common.Session
	0, // 7: conabit.englearn.exercise.WordService.RegisterWordPair:output_type -> conabit.englearn.exercise.WordPair
	0, // 8: conabit.englearn.exercise.WordService.CloneWordPair:output_type -> conabit.englearn.exercise.WordPair
	0, // 9: conabit.englearn.exercise.WordService.FindUserWords:output_type -> conabit.englearn.exercise.WordPair
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_conabit_englearn_exercise_word_service_proto_init() }
func file_proto_conabit_englearn_exercise_word_service_proto_init() {
	if File_proto_conabit_englearn_exercise_word_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWordPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_conabit_englearn_exercise_word_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneWordPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_conabit_englearn_exercise_word_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_conabit_englearn_exercise_word_service_proto_goTypes,
		DependencyIndexes: file_proto_conabit_englearn_exercise_word_service_proto_depIdxs,
		MessageInfos:      file_proto_conabit_englearn_exercise_word_service_proto_msgTypes,
	}.Build()
	File_proto_conabit_englearn_exercise_word_service_proto = out.File
	file_proto_conabit_englearn_exercise_word_service_proto_rawDesc = nil
	file_proto_conabit_englearn_exercise_word_service_proto_goTypes = nil
	file_proto_conabit_englearn_exercise_word_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WordServiceClient is the client API for WordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordServiceClient interface {
	RegisterWordPair(ctx context.Context, in *RegisterWordPairRequest, opts ...grpc.CallOption) (*WordPair, error)
	CloneWordPair(ctx context.Context, in *CloneWordPairRequest, opts ...grpc.CallOption) (*WordPair, error)
	FindUserWords(ctx context.Context, in *common.Session, opts ...grpc.CallOption) (WordService_FindUserWordsClient, error)
}

type wordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordServiceClient(cc grpc.ClientConnInterface) WordServiceClient {
	return &wordServiceClient{cc}
}

func (c *wordServiceClient) RegisterWordPair(ctx context.Context, in *RegisterWordPairRequest, opts ...grpc.CallOption) (*WordPair, error) {
	out := new(WordPair)
	err := c.cc.Invoke(ctx, "/conabit.englearn.exercise.WordService/RegisterWordPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordServiceClient) CloneWordPair(ctx context.Context, in *CloneWordPairRequest, opts ...grpc.CallOption) (*WordPair, error) {
	out := new(WordPair)
	err := c.cc.Invoke(ctx, "/conabit.englearn.exercise.WordService/CloneWordPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordServiceClient) FindUserWords(ctx context.Context, in *common.Session, opts ...grpc.CallOption) (WordService_FindUserWordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WordService_serviceDesc.Streams[0], "/conabit.englearn.exercise.WordService/FindUserWords", opts...)
	if err != nil {
		return nil, err
	}
	x := &wordServiceFindUserWordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WordService_FindUserWordsClient interface {
	Recv() (*WordPair, error)
	grpc.ClientStream
}

type wordServiceFindUserWordsClient struct {
	grpc.ClientStream
}

func (x *wordServiceFindUserWordsClient) Recv() (*WordPair, error) {
	m := new(WordPair)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WordServiceServer is the server API for WordService service.
type WordServiceServer interface {
	RegisterWordPair(context.Context, *RegisterWordPairRequest) (*WordPair, error)
	CloneWordPair(context.Context, *CloneWordPairRequest) (*WordPair, error)
	FindUserWords(*common.Session, WordService_FindUserWordsServer) error
}

// UnimplementedWordServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWordServiceServer struct {
}

func (*UnimplementedWordServiceServer) RegisterWordPair(context.Context, *RegisterWordPairRequest) (*WordPair, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWordPair not implemented")
}
func (*UnimplementedWordServiceServer) CloneWordPair(context.Context, *CloneWordPairRequest) (*WordPair, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneWordPair not implemented")
}
func (*UnimplementedWordServiceServer) FindUserWords(*common.Session, WordService_FindUserWordsServer) error {
	return status.Errorf(codes.Unimplemented, "method FindUserWords not implemented")
}

func RegisterWordServiceServer(s *grpc.Server, srv WordServiceServer) {
	s.RegisterService(&_WordService_serviceDesc, srv)
}

func _WordService_RegisterWordPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWordPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).RegisterWordPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conabit.englearn.exercise.WordService/RegisterWordPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).RegisterWordPair(ctx, req.(*RegisterWordPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordService_CloneWordPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneWordPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).CloneWordPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conabit.englearn.exercise.WordService/CloneWordPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).CloneWordPair(ctx, req.(*CloneWordPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordService_FindUserWords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.Session)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WordServiceServer).FindUserWords(m, &wordServiceFindUserWordsServer{stream})
}

type WordService_FindUserWordsServer interface {
	Send(*WordPair) error
	grpc.ServerStream
}

type wordServiceFindUserWordsServer struct {
	grpc.ServerStream
}

func (x *wordServiceFindUserWordsServer) Send(m *WordPair) error {
	return x.ServerStream.SendMsg(m)
}

var _WordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conabit.englearn.exercise.WordService",
	HandlerType: (*WordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWordPair",
			Handler:    _WordService_RegisterWordPair_Handler,
		},
		{
			MethodName: "CloneWordPair",
			Handler:    _WordService_CloneWordPair_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindUserWords",
			Handler:       _WordService_FindUserWords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/conabit/englearn/exercise/word_service.proto",
}
