FROM golang:1.17-alpine

RUN apk add --no-cache bash make gcc g++ python linux-headers udev --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main gdal gdal-dev

RUN mkdir -p /app

WORKDIR /app

COPY auth-service.bin .

EXPOSE 4000

CMD [ "/app/auth-service.bin" ]
