export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"
export const OPEN_CONFIRMALERT = "OPEN_CONFIRMALERT";
export const CLOSE_CONFIRMALERT = "CLOSE_CONFIRMALERT";

